# Generated by Django 4.1.2 on 2023-03-26 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='CId',
            field=models.UUIDField(),
        ),
    ]
