# Generated by Django 4.1.2 on 2023-03-27 13:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App_Article', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogcomment',
            options={},
        ),
        migrations.RemoveField(
            model_name='blogcomment',
            name='id',
        ),
        migrations.AddField(
            model_name='blogcomment',
            name='custom_id',
            field=models.CharField(default=uuid.uuid4, max_length=10, primary_key=True, serialize=False),
        ),
    ]
