# Generated by Django 4.1.2 on 2022-10-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Article', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(default='Articles/defualt.jpg', upload_to='Articles/', verbose_name='Image'),
        ),
    ]
