# Generated by Django 4.1.2 on 2023-03-27 13:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('App_Article', '0002_alter_blogcomment_options_remove_blogcomment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='custom_id',
            field=models.CharField(default=uuid.uuid4, max_length=8, primary_key=True, serialize=False),
        ),
    ]
