# Generated by Django 4.1.2 on 2023-06-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Article', '0002_alter_blogpost_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloglike',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
