# Generated by Django 4.1.2 on 2022-10-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Article', '0002_alter_blogpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='description',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='published',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
