# Generated by Django 4.1.2 on 2022-10-22 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Article', '0003_remove_blogpost_category_remove_blogpost_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='image',
        ),
    ]
