# Generated by Django 4.1.2 on 2023-03-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Article', '0003_bloglike_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='comment',
            field=models.CharField(max_length=500),
        ),
    ]
