# Generated by Django 4.1.2 on 2023-03-27 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Article', '0003_alter_blogcomment_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='custom_id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
