# Generated by Django 4.1.2 on 2022-10-22 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Article', '0004_remove_blogpost_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='publish_date',
        ),
        migrations.RemoveField(
            model_name='blogpost',
            name='update_date',
        ),
    ]
