# Generated by Django 4.1.2 on 2023-03-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Article', '0004_alter_blogcomment_custom_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='publish_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
