# Generated by Django 4.1.2 on 2023-05-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Article', '0005_alter_blogpost_publish_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
