# Generated by Django 4.1.2 on 2023-05-18 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Article', '0006_alter_blogpost_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
