# Generated by Django 4.1.2 on 2023-05-22 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Article', '0011_alter_blogpost_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='published',
            field=models.IntegerField(),
        ),
    ]
